#generated by Git for Windows
if [ -f ~/tools/envr_settings/.bashrc ]; then
    . ~/tools/envr_settings/.bashrc
elif [ -f /localdisk2/loberto/tools/envr_settings/.bashrc ]; then
    . /localdisk2/loberto/tools/envr_settings/.bashrc
elif [ -f d:/iusers/loberto/tools/envr_settings/.bashrc ]; then
    . d:/iusers/loberto/tools/envr_settings/.bashrc
else
    . ~/.bashrc
fi
